networks:
  mongo:
  mysql:
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - mongo
    restart: always
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - mysql
    restart: always
  patient_service:
    build: ./patient_service
    container_name: patient-service
    ports:
      - "8100:8100"
    depends_on:
      - mysql
    networks:
      - mysql
    restart: always
  doctor_service:
    build: ./doctor_service
    container_name: doctor-service
    ports:
      - "8200:8200"
    depends_on:
      - mongo
    networks:
      - mongo
    restart: always
  appointment_service:
    build: ./appointment-service
    container_name: appointment_service
    ports:
      - "8300:8300"
    depends_on:
      - mysql
      - mongo
    networks:
      - mysql
      - mongo
    restart: always